spring.application.name=tcc123

spring.datasource.url=jdbc:postgresql://ep-quiet-mountain-a4676tbw-pooler.us-east-1.aws.neon.tech:5432/verceldb
spring.datasource.username=default
spring.datasource.password=dihVPg53ZEMN
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
